### ISSUE TITLE
Feedback on trailingSlash option + GH Pages

### ISSUE THREAD

**Issue by jsamr** [slorber/trailing-slash-guide#2]
@slorber 

## Issue / Bug?

I've set `"trailingSlash": false` on my project following suggestions by the CLI. I have a non-empty base-url, and here is what happens when fetching https://meliorence.github.io/react-native-render-html:

```bash
> http -h https://meliorence.github.io/react-native-render-html
HTTP/1.1 301 Moved Permanently
Location: https://meliorence.github.io/react-native-render-html/
...
```
OK, so GH pages redirects the root (a file named react-native-render-html.html in the gh-pages branch) to the slash-forwards path.  That's not great for SEO (unless the sitemap reflects that), but at least if it works... Let's fetch the redirected-url:

```bash
> http -h https://meliorence.github.io/react-native-render-html/
HTTP/1.1 200 OK
```
Good.... However, if you try that out in a browser, you'll see a "Not Found" flash. My understanding of what's happening:

1. The browser loads the static HTML asset, build the DOM and paints.
2. The DOM is hydrated.
3. Docusaurus router (if there is such thing) finds that this route is a mismatch because of the trailingSlash option. It thus flashes a "Not Found" route after which it manages to find the actual route.

https://user-images.githubusercontent.com/3646758/123512769-b3b2aa80-d65f-11eb-9c79-a1845c0c7eb7.mp4

## Workaround

After a docusaurus build, the gh-pages branch folder structure looks like this:

<pre>
├── api
├── assets
├── blog
├── docs
├── favicons
├── img
├── video
├── 404.html
├── api.html
├── blog.html
├── opensearch.xml
<strong>├── react-native-render-html.html</strong>
├── search.html
└── sitemap.xml
</pre>

By copying `react-native-render-html.html` into `index.html` and pushing, the "Not Found" flash bug disappears.

## Additional information

@docusaurus/*@2.0.0-beta.4d93c894f

## Remarks

Ideally, the sitemap generated for gh-pages would add a trailing slash to the root URL to avoid redirects, or there could be an option to deal with the root.

**Comment by slorber** [comment]
Hi!

This project is not directly related to Docusaurus so can you re-open this issue on Docusaurus instead?

I'll look at this on Monday anyway
It makes me think about another issue opened recently (https://github.com/facebook/docusaurus/issues/5055)

```
├── react-native-render-html.html
```

I don't understand, Docusaurus does not create an `index.html` file anymore in beta.2, while it did before?

Can you deploy your site with the bug somewhere (a fork?), so that I can see the live site + have the ability to inspect the gh-branch?

**Comment by jsamr** [comment]
@slorber All right, I'll try to make a reproduction and file a report. I didn't report on Docusaurus because I wasn't sure it's really a bug...

> I don't think, we don't want to hardcode special cases per host.

Sure hardcoding is bad, however there could be an actionable solution for all those who're using GH pages and don't want to suffer from degraded SEO. Perhaps `trailingSlash: 'root'` meaning, one trailing slash is expected for the top level route, no trailing slash for other routes. That would match per-repository GH Pages deployments.

**Comment by slorber** [comment]
Yes we should provide options so that it works fine with GH pages, it was
the purpose of trailingSlash: false

If it doesn't work we should just fix it. I surprised because someone has
confirmed trailingSlash: false was working fine on his GH pages site, so
I'll have to investigate this

**Comment by jsamr** [comment]
Closing in favor of https://github.com/facebook/docusaurus/issues/5077
